networks:
  internal:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      internal:

  migration:
    build: .
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate
    networks:
      internal:

  seed_db:
    build: .
    env_file: .env
    depends_on:
      migration:
        condition: service_completed_successfully
    command: python manage.py loaddata items.json
    networks:
      internal:

  django:
    build: .
    container_name: django
    env_file:
      - .env
    depends_on:
      seed_db:
        condition: service_completed_successfully
    command: python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      internal:
